services:
  db:
    container_name: db
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
  pyauth:
    container_name: pyauth
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./config:/config
      - ./pyauth:/app/pyauth
    depends_on:
      db:
        condition: service_healthy
